import React from "react";

const TermsAndConditions = () => {
  return (
    <div className="container mx-auto max-w-4xl px-4 py-10 my-7">
      {/* Page Title */}
      <h1 className="scroll-m-20 text-4xl font-bold tracking-tight">
        Terms & Conditions
      </h1>

      <p className="mt-4 text-sm text-muted-foreground">
        Disclaimer: In case of any discrepancy or difference, the English
        version will take precedence over the translation.
      </p>

      {/* Intro */}
      <section className="mt-8 space-y-4">
        <p className="leading-7">
          This document is an electronic record in terms of the Information
          Technology Act, 2000 and rules made thereunder. This electronic record
          is generated by a computer system and does not require any physical or
          digital signatures.
        </p>

        <p className="leading-7">
          These Terms of Use govern your access to and use of the UniDrobe
          website, mobile site, and mobile application (collectively, the
          “Platform”). By accessing, browsing, or using the Platform, you agree
          to be bound by these Terms.
        </p>
      </section>

      {/* Membership Eligibility */}
      <section className="mt-10 space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold">
          Membership Eligibility
        </h2>

        <p className="leading-7">
          Transactions on the Platform are available only to persons who can
          form legally binding contracts under the Indian Contract Act, 1872.
          Persons who are “incompetent to contract” are not eligible to use the
          Platform.
        </p>

        <p className="leading-7">
          If you are under the age of 18, you may use the Platform only under
          the supervision of a parent or legal guardian.
        </p>
      </section>

      {/* User Account */}
      <section className="mt-10 space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold">
          User Account & Registration
        </h2>

        <p className="leading-7">
          You are responsible for maintaining the confidentiality of your
          account credentials and for all activities that occur under your
          account. UniDrobe shall not be liable for any loss arising from
          unauthorized use of your account.
        </p>

        <p className="leading-7">
          You agree to provide accurate, current, and complete information
          during registration and to update such information as necessary.
        </p>
      </section>

      {/* Platform Role */}
      <section className="mt-10 space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold">
          Platform for Transactions
        </h2>

        <p className="leading-7">
          UniDrobe is a marketplace platform that enables buyers and sellers
          to transact. UniDrobe is not a party to the contract between buyers
          and sellers and does not assume liability for product quality,
          delivery, or after-sales services.
        </p>

        <p className="leading-7">
          All commercial terms including price, shipping, and warranties are
          determined solely by the sellers.
        </p>
      </section>

      {/* Payments */}
      <section className="mt-10 space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold">
          Payments & Refunds
        </h2>

        <p className="leading-7">
          Payments on the Platform must be made in Indian Rupees using
          authorized payment methods. UniDrobe does not store payment card
          details.
        </p>

        <p className="leading-7">
          Refunds, if applicable, will be processed as per the Refund Policy
          and credited to the original payment method or other approved modes.
        </p>
      </section>

      {/* Prohibited Use */}
      <section className="mt-10 space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold">
          Prohibited Activities
        </h2>

        <ul className="ml-6 list-disc space-y-2 text-sm leading-6">
          <li>Uploading unlawful, abusive, defamatory, or obscene content</li>
          <li>Violating intellectual property rights</li>
          <li>Attempting unauthorized access to the Platform</li>
          <li>Engaging in fraudulent or misleading activities</li>
          <li>Using automated tools to scrape or misuse data</li>
        </ul>
      </section>

      {/* Limitation */}
      <section className="mt-10 space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold">
          Disclaimer & Limitation of Liability
        </h2>

        <p className="leading-7">
          The Platform and all services are provided on an “as is” and “as
          available” basis. UniDrobe makes no warranties, express or implied.
        </p>

        <p className="leading-7">
          UniDrobe shall not be liable for any indirect, incidental, or
          consequential damages arising from use of the Platform.
        </p>
      </section>

      {/* Governing Law */}
      <section className="mt-10 space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold">
          Governing Law & Jurisdiction
        </h2>

        <p className="leading-7">
          These Terms shall be governed and interpreted in accordance with the
          laws of India. Courts located in India shall have exclusive
          jurisdiction.
        </p>
      </section>

      {/* Changes */}
      <section className="mt-10 space-y-4">
        <h2 className="scroll-m-20 border-b pb-2 text-2xl font-semibold">
          Amendments
        </h2>

        <p className="leading-7">
          UniDrobe reserves the right to modify these Terms at any time. Your
          continued use of the Platform constitutes acceptance of the revised
          Terms.
        </p>
      </section>

      {/* Footer */}
      <p className="mt-12 text-xs text-muted-foreground">
        © {new Date().getFullYear()} UniDrobe. All rights reserved.
      </p>
    </div>
  );
};

export default TermsAndConditions;
